/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', 'class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
  	extend: {
  		colors: {
  			gray: {
  				'1': 'var(--gray-1)',
  				'2': 'var(--gray-2)',
  				'3': 'var(--gray-3)',
  				'4': 'var(--gray-4)',
  				'5': 'var(--gray-5)',
  				'6': 'var(--gray-6)',
  				'7': 'var(--gray-7)',
  				'8': 'var(--gray-8)',
  				'9': 'var(--gray-9)',
  				'10': 'var(--gray-10)',
  				'11': 'var(--gray-11)',
  				'12': 'var(--gray-12)',
  				a1: 'var(--gray-a1)',
  				a2: 'var(--gray-a2)',
  				a3: 'var(--gray-a3)',
  				a4: 'var(--gray-a4)',
  				a5: 'var(--gray-a5)',
  				a6: 'var(--gray-a6)',
  				a7: 'var(--gray-a7)',
  				a8: 'var(--gray-a8)',
  				a9: 'var(--gray-a9)',
  				a10: 'var(--gray-a10)',
  				a11: 'var(--gray-a11)',
  				a12: 'var(--gray-a12)'
  			},
  			red: {
  				'1': 'var(--red-1)',
  				'2': 'var(--red-2)',
  				'3': 'var(--red-3)',
  				'4': 'var(--red-4)',
  				'5': 'var(--red-5)',
  				'6': 'var(--red-6)',
  				'7': 'var(--red-7)',
  				'8': 'var(--red-8)',
  				'9': 'var(--red-9)',
  				'10': 'var(--red-10)',
  				'11': 'var(--red-11)',
  				'12': 'var(--red-12)',
  				a1: 'var(--red-a1)',
  				a2: 'var(--red-a2)',
  				a3: 'var(--red-a3)',
  				a4: 'var(--red-a4)',
  				a5: 'var(--red-a5)',
  				a6: 'var(--red-a6)',
  				a7: 'var(--red-a7)',
  				a8: 'var(--red-a8)',
  				a9: 'var(--red-a9)',
  				a10: 'var(--red-a10)',
  				a11: 'var(--red-a11)',
  				a12: 'var(--red-a12)'
  			},
  			grayContrast: 'var(--gray-contrast)',
  			graySurface: 'var(--gray-surface)',
  			grayIndicator: 'var(--gray-indicator)',
  			grayTrack: 'var(--gray-track)',
  			redContrast: 'var(--red-contrast)',
  			redSurface: 'var(--red-surface)',
  			redIndicator: 'var(--red-indicator)',
  			redTrack: 'var(--red-track)',
  			plum1: '#fefcff',
  			plum2: '#fdf7fd',
  			plum3: '#fbebfb',
  			plum4: '#f7def8',
  			plum5: '#f2d1f3',
  			plum6: '#e9c2ec',
  			plum7: '#deade3',
  			plum8: '#cf91d8',
  			plum9: '#ab4aba',
  			plum10: '#a144af',
  			plum11: '#953ea3',
  			plum12: '#53195d',
  			bronze1: '#fdfcfc',
  			bronze2: '#fdf7f5',
  			bronze3: '#f6edea',
  			bronze4: '#efe4df',
  			bronze5: '#e7d9d3',
  			bronze6: '#dfcdc5',
  			bronze7: '#d3bcb3',
  			bronze8: '#c2a499',
  			bronze9: '#a18072',
  			bronze10: '#957468',
  			bronze11: '#7d5e54',
  			bronze12: '#43302b',
  			brown1: 'hsl(30, 50%, 99%)',
  			brown2: 'hsl(30, 50%, 98%)',
  			brown3: 'hsl(28, 45%, 94%)',
  			brown4: 'hsl(29, 43%, 90%)',
  			brown5: 'hsl(29, 45%, 86%)',
  			brown6: 'hsl(29, 45%, 81%)',
  			brown7: 'hsl(29, 47%, 74%)',
  			brown8: 'hsl(28, 45%, 65%)',
  			brown9: 'hsl(28, 34%, 51%)',
  			brown10: 'hsl(26, 32%, 48%)',
  			brown11: 'hsl(24, 30%, 39%)',
  			brown12: 'hsl(19, 15%, 21%)',
  			mint1: '#f9fefd',
  			mint2: '#f2fbf9',
  			mint3: '#ddf9f2',
  			mint4: '#c8f4e9',
  			mint5: '#b3ecde',
  			mint6: '#9ce0d0',
  			mint7: '#7ecfbd',
  			mint8: '#4cbba5',
  			mint9: '#86ead4',
  			mint10: '#7de0cb',
  			mint11: '#027864',
  			mint12: '#16433c',
  			slate1: '#fcfcfd',
  			slate2: '#f9f9fb',
  			slate3: '#f0f0f3',
  			slate4: '#e8e8ec',
  			slate5: '#e0e1e6',
  			slate6: '#d9d9e0',
  			slate7: '#cdced6',
  			slate8: '#b9bbc6',
  			slate9: '#8b8d98',
  			slate10: '#80838d',
  			slate11: '#60646c',
  			slate12: '#1c2024',
  			jade1: '#fbfefd',
  			jade2: '#f4fbf7',
  			jade3: '#e6f7ed',
  			jade4: '#d6f1e3',
  			jade5: '#c3e9d7',
  			jade6: '#acdec8',
  			jade7: '#8bceb6',
  			jade8: '#56ba9f',
  			jade9: '#29a383',
  			jade10: '#26997b',
  			jade11: '#208368',
  			jade12: '#1d3b31',
  			iris1: '#fdfdff',
  			iris2: '#f8f8ff',
  			iris3: '#f0f1fe',
  			iris4: '#e6e7ff',
  			iris5: '#dadcff',
  			iris6: '#cbcdff',
  			iris7: '#b8baf8',
  			iris8: '#9b9ef0',
  			iris9: '#5b5bd6',
  			iris10: '#5151cd',
  			iris11: '#5753c6',
  			iris12: '#272962',
  			background: 'hsl(var(--background))',
  			foreground: 'hsl(var(--foreground))',
  			card: {
  				DEFAULT: 'hsl(var(--card))',
  				foreground: 'hsl(var(--card-foreground))'
  			},
  			popover: {
  				DEFAULT: 'hsl(var(--popover))',
  				foreground: 'hsl(var(--popover-foreground))'
  			},
  			primary: {
  				DEFAULT: 'hsl(var(--primary))',
  				foreground: 'hsl(var(--primary-foreground))'
  			},
  			secondary: {
  				DEFAULT: 'hsl(var(--secondary))',
  				foreground: 'hsl(var(--secondary-foreground))'
  			},
  			muted: {
  				DEFAULT: 'hsl(var(--muted))',
  				foreground: 'hsl(var(--muted-foreground))'
  			},
  			accent: {
  				DEFAULT: 'hsl(var(--accent))',
  				foreground: 'hsl(var(--accent-foreground))'
  			},
  			destructive: {
  				DEFAULT: 'hsl(var(--destructive))',
  				foreground: 'hsl(var(--destructive-foreground))'
  			},
  			border: 'hsl(var(--border))',
  			input: 'hsl(var(--input))',
  			ring: 'hsl(var(--ring))',
  			chart: {
  				'1': 'hsl(var(--chart-1))',
  				'2': 'hsl(var(--chart-2))',
  				'3': 'hsl(var(--chart-3))',
  				'4': 'hsl(var(--chart-4))',
  				'5': 'hsl(var(--chart-5))'
  			}
  		},
  		backgroundImage: {
  			'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
  			'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))'
  		},
  		borderRadius: {
  			lg: 'var(--radius)',
  			md: 'calc(var(--radius) - 2px)',
  			sm: 'calc(var(--radius) - 4px)'
  		}
  	}
  },
  plugins: [require("tailwindcss-animate")],
}
