import { Header, Footer } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import { IBM_Plex_Sans } from 'next/font/google'

const ibmPlexSans = IBM_Plex_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: 'Tahir Ahmed',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.className} flex flex-col bg-slate2 min-h-screen`}
      >
        <Header />
        <>{children}</>
        <Footer />
      </body>
    </html>
  )
}
