import { Header, Footer, ThemeProvider } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import { Hind_Madurai } from 'next/font/google'

const ibmPlexSans = Hind_Madurai({
  weight: ['300', '400', '500', '600', '700'],
  // weight: ['400', '700'],
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: 'Tahir Ahmed',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.className} flex flex-col bg-red-1 min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          {/* <div className="absolute inset-0  "></div> */}
          <main className="bg-gradient-to-b from-15% from-red-5 dark:from-red-4 to-transparent h-96">
            <Header />
            {children}
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
